CREATE TABLE /*_*/pcp_diagnosis_abbreviations (
    da_id        INT UNSIGNED NOT NULL AUTO_INCREMENT,
    da_token     VARCHAR(64)  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    da_system    VARCHAR(32)  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    da_code      VARCHAR(64)  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
    da_canonical VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    PRIMARY KEY (da_id),
    KEY /*i*/da_token (da_token)
) /*$wgDBTableOptions*/;

-- Seed rows are appended below by the abbreviation_seed dump.
-- Seed data: 95 rows
INSERT INTO /*_*/pcp_diagnosis_abbreviations (da_token, da_system, da_code, da_canonical) VALUES
    ( 'mdd', 'DSM-5', '296.xx', 'Major Depressive Disorder' ),
    ( 'mde', 'DSM-5', NULL, 'Major Depressive Episode' ),
    ( 'pmdd', 'DSM-5', 'N94.3', 'Premenstrual Dysphoric Disorder' ),
    ( 'pdd', 'DSM-5', '300.4', 'Persistent Depressive Disorder (Dysthymia)' ),
    ( 'dysthymia', 'DSM-5', '300.4', 'Persistent Depressive Disorder (Dysthymia)' ),
    ( 'sad', 'DSM-5', NULL, 'Seasonal Affective Disorder' ),
    ( 'dmdd', 'DSM-5', NULL, 'Disruptive Mood Dysregulation Disorder' ),
    ( 'bpad', 'DSM-5', NULL, 'Bipolar Affective Disorder' ),
    ( 'bd', 'DSM-5', NULL, 'Bipolar Disorder' ),
    ( 'bd1', 'DSM-5', '296.4x', 'Bipolar I Disorder' ),
    ( 'bd2', 'DSM-5', '296.89', 'Bipolar II Disorder' ),
    ( 'bad', 'DSM-5', NULL, 'Bipolar Affective Disorder' ),
    ( 'bad1', 'DSM-5', '296.4x', 'Bipolar I Disorder' ),
    ( 'bad2', 'DSM-5', '296.89', 'Bipolar II Disorder' ),
    ( 'cyclothymia', 'DSM-5', '301.13', 'Cyclothymic Disorder' ),
    ( 'gad', 'DSM-5', '300.02', 'Generalized Anxiety Disorder' ),
    ( 'sad-soc', 'DSM-5', '300.23', 'Social Anxiety Disorder' ),
    ( 'social-anxiety', 'DSM-5', '300.23', 'Social Anxiety Disorder' ),
    ( 'panic-disorder', 'DSM-5', '300.01', 'Panic Disorder' ),
    ( 'agoraphobia', 'DSM-5', '300.22', 'Agoraphobia' ),
    ( 'ocd', 'DSM-5', '300.3', 'Obsessive-Compulsive Disorder' ),
    ( 'bdd', 'DSM-5', '300.7', 'Body Dysmorphic Disorder' ),
    ( 'hoarding', 'DSM-5', '300.3', 'Hoarding Disorder' ),
    ( 'trich', 'DSM-5', '312.39', 'Trichotillomania' ),
    ( 'ptsd', 'DSM-5', '309.81', 'Posttraumatic Stress Disorder' ),
    ( 'cptsd', 'ICD-11', '6B41', 'Complex Post-Traumatic Stress Disorder' ),
    ( 'c-ptsd', 'ICD-11', '6B41', 'Complex Post-Traumatic Stress Disorder' ),
    ( 'asd', 'DSM-5', '308.3', 'Acute Stress Disorder' ),
    ( 'adhd', 'DSM-5', '314.xx', 'Attention-Deficit/Hyperactivity Disorder' ),
    ( 'add', 'DSM-5', '314.00', 'Attention Deficit Disorder (predominantly inattentive)' ),
    ( 'asd-autism', 'DSM-5', '299.00', 'Autism Spectrum Disorder' ),
    ( 'autism', 'DSM-5', '299.00', 'Autism Spectrum Disorder' ),
    ( 'tourette', 'DSM-5', '307.23', 'Tourette Syndrome' ),
    ( 'fasd', 'ICD-10', 'Q86.0', 'Fetal Alcohol Spectrum Disorder' ),
    ( 'dyslexia', 'DSM-5', '315.0', 'Specific Learning Disorder with Dyslexia' ),
    ( 'dyscalculia', 'DSM-5', '315.1', 'Specific Learning Disorder with Dyscalculia' ),
    ( 'bpd', 'DSM-5', '301.83', 'Borderline Personality Disorder' ),
    ( 'npd', 'DSM-5', '301.81', 'Narcissistic Personality Disorder' ),
    ( 'avpd', 'DSM-5', '301.82', 'Avoidant Personality Disorder' ),
    ( 'scpd', 'DSM-5', '301.20', 'Schizoid Personality Disorder' ),
    ( 'stpd', 'DSM-5', '301.22', 'Schizotypal Personality Disorder' ),
    ( 'hpd', 'DSM-5', '301.50', 'Histrionic Personality Disorder' ),
    ( 'ocpd', 'DSM-5', '301.4', 'Obsessive-Compulsive Personality Disorder' ),
    ( 'aspd', 'DSM-5', '301.7', 'Antisocial Personality Disorder' ),
    ( 'ppd', 'DSM-5', '301.0', 'Paranoid Personality Disorder' ),
    ( 'dpd', 'DSM-5', '301.6', 'Dependent Personality Disorder' ),
    ( 'sz', 'DSM-5', '295.xx', 'Schizophrenia' ),
    ( 'schizo', 'DSM-5', '295.xx', 'Schizophrenia' ),
    ( 'szaff', 'DSM-5', '295.70', 'Schizoaffective Disorder' ),
    ( 'szaffd', 'DSM-5', '295.70', 'Schizoaffective Disorder' ),
    ( 'ed', 'DSM-5', NULL, 'Eating Disorder' ),
    ( 'an', 'DSM-5', '307.1', 'Anorexia Nervosa' ),
    ( 'bn', 'DSM-5', '307.51', 'Bulimia Nervosa' ),
    ( 'bed', 'DSM-5', '307.51', 'Binge-Eating Disorder' ),
    ( 'arfid', 'DSM-5', '307.59', 'Avoidant/Restrictive Food Intake Disorder' ),
    ( 'osa', 'ICD-10', 'G47.33', 'Obstructive Sleep Apnea' ),
    ( 'rls', 'ICD-10', 'G25.81', 'Restless Legs Syndrome' ),
    ( 'did', 'DSM-5', '300.14', 'Dissociative Identity Disorder' ),
    ( 'osdd', 'DSM-5', '300.15', 'Other Specified Dissociative Disorder' ),
    ( 'dpdr', 'DSM-5', '300.6', 'Depersonalization/Derealization Disorder' ),
    ( 'aud', 'DSM-5', '303.90', 'Alcohol Use Disorder' ),
    ( 'oud', 'DSM-5', '304.0', 'Opioid Use Disorder' ),
    ( 'cud', 'DSM-5', '304.30', 'Cannabis Use Disorder' ),
    ( 'sud', 'DSM-5', NULL, 'Stimulant Use Disorder' ),
    ( 'rsd', 'unofficial', NULL, 'Rejection Sensitivity Dysphoria' ),
    ( 'rejection-sensitivity', 'unofficial', NULL, 'Rejection Sensitivity Dysphoria' ),
    ( 'misophonia', 'unofficial', NULL, 'Misophonia' ),
    ( 'hsp', 'unofficial', NULL, 'Highly Sensitive Person / Sensory Processing Sensitivity' ),
    ( 'spd', 'unofficial', NULL, 'Sensory Processing Disorder' ),
    ( 'hspd', 'unofficial', NULL, 'Sensory Processing Sensitivity' ),
    ( 'mcas', 'somatic', NULL, 'Mast Cell Activation Syndrome' ),
    ( 'pots', 'somatic', 'G90.A', 'Postural Orthostatic Tachycardia Syndrome' ),
    ( 'eds', 'somatic', 'Q79.6', 'Ehlers-Danlos Syndrome' ),
    ( 'heds', 'somatic', 'Q79.6', 'Hypermobile Ehlers-Danlos Syndrome' ),
    ( 'hsd', 'somatic', NULL, 'Hypermobility Spectrum Disorder' ),
    ( 'fibro', 'somatic', 'M79.7', 'Fibromyalgia' ),
    ( 'fibromyalgia', 'somatic', 'M79.7', 'Fibromyalgia' ),
    ( 'mecfs', 'somatic', 'G93.3', 'Myalgic Encephalomyelitis / Chronic Fatigue Syndrome' ),
    ( 'cfs', 'somatic', 'G93.3', 'Chronic Fatigue Syndrome' ),
    ( 'ibs', 'somatic', 'K58', 'Irritable Bowel Syndrome' ),
    ( 'ibd', 'somatic', 'K50-K51', 'Inflammatory Bowel Disease' ),
    ( 'migraine', 'ICD-10', 'G43', 'Migraine' ),
    ( 'psa', 'somatic', 'L40.5', 'Psoriatic Arthritis' ),
    ( 'ra', 'somatic', 'M05', 'Rheumatoid Arthritis' ),
    ( 'ms', 'somatic', 'G35', 'Multiple Sclerosis' ),
    ( 't1d', 'somatic', 'E10', 'Type 1 Diabetes Mellitus' ),
    ( 't2d', 'somatic', 'E11', 'Type 2 Diabetes Mellitus' ),
    ( 'hypothyroid', 'somatic', 'E03', 'Hypothyroidism' ),
    ( 'hyperthyroid', 'somatic', 'E05', 'Hyperthyroidism' ),
    ( 'pcos', 'somatic', 'E28.2', 'Polycystic Ovary Syndrome' ),
    ( 'endometriosis', 'somatic', 'N80', 'Endometriosis' ),
    ( 'tbi', 'ICD-10', 'S06', 'Traumatic Brain Injury' ),
    ( 'fnd', 'ICD-10', 'F44', 'Functional Neurological Disorder' ),
    ( 'gad-7', 'instrument', NULL, 'GAD-7 (Generalized Anxiety Disorder 7-item scale)' ),
    ( 'phq-9', 'instrument', NULL, 'PHQ-9 (Patient Health Questionnaire 9-item)' );
