CREATE TABLE /*_*/pcp_literature (
    l_id            INT UNSIGNED NOT NULL AUTO_INCREMENT,
    l_page_id       INT UNSIGNED NOT NULL,
    l_voter_hash    VARBINARY(64) NOT NULL,
    l_display_name  VARBINARY(255) DEFAULT NULL,
    l_status        TINYINT NOT NULL DEFAULT 0,
    l_authors       VARBINARY(500) DEFAULT NULL,
    l_et_al         TINYINT NOT NULL DEFAULT 0,
    l_title         VARBINARY(500) NOT NULL,
    l_year          SMALLINT UNSIGNED DEFAULT NULL,
    l_url           VARBINARY(2048) DEFAULT NULL,
    l_doi           VARBINARY(255) DEFAULT NULL,
    l_pmid          INT UNSIGNED DEFAULT NULL,
    l_file_path     VARBINARY(255) DEFAULT NULL,
    l_file_origname VARBINARY(255) DEFAULT NULL,
    l_file_mime     VARBINARY(64) DEFAULT NULL,
    l_file_size     INT UNSIGNED DEFAULT NULL,
    l_admin_notes   BLOB DEFAULT NULL,
    l_reviewed_by   INT UNSIGNED DEFAULT NULL,
    l_submitted     BINARY(14) NOT NULL,
    l_reviewed      BINARY(14) DEFAULT NULL,
    PRIMARY KEY (l_id),
    KEY /*i*/l_page_status (l_page_id, l_status),
    KEY /*i*/l_status_submitted (l_status, l_submitted),
    KEY /*i*/l_voter_hash (l_voter_hash),
    KEY /*i*/l_doi (l_doi(64)),
    KEY /*i*/l_pmid (l_pmid)
) /*$wgDBTableOptions*/;
